#!/bin/bash
#By Hamed Ap
# Example : adduser hamed 123 

sudo useradd -M $1  &
wait

sudo adduser $1 jailed &
wait


sudo passwd $1 <<!
$2
$2
!

FILE=/etc/ocserv/ocpasswd
if test -f "$FILE"; then
    sudo ocpasswd -c /etc/ocserv/ocpasswd $1 <<< $2
fi